FROM golang as exec

COPY ./main.go /go/src/app/

ENV GO111MODULE=auto

WORKDIR /go/src/app

RUN [ "go", "build", "-o", "main.go", "." ]

FROM alpine

WORKDIR /appexec

COPY --from=exec /go/src/app/main.go /appexec/

RUN [ "chmod", "-R", "755", "/appexec" ]

ENTRYPOINT [ "./main.go" ]